//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import os
        ///from enum import Enum, unique, auto
        ///
        ///#constants
        ///
        ///def __getExt(fileName):
        ///    if &apos;.&apos; in fileName: return os.path.splitext(fileName)[1].replace(&apos;.&apos;, &apos;&apos;)
        ///    else: return fileName
        ///
        ///&quot;&quot;&quot;
        ///Methods for translating between mime-types and file extensions
        ///&quot;&quot;&quot;
        ///def getMimeType(fileName):
        ///    &quot;&quot;&quot;
        ///    Returns the mime type for the given file name
        ///    :param str fileName A file name, file extension or file path specification
        ///    &quot;&quot;&quot;
        ///    extension = __getExt(fileName)
        ///    #getMimeType body
        ///
        ///def [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JavascriptClass {
            get {
                return ResourceManager.GetString("JavascriptClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import os
        ///from enum import Enum, unique, auto
        ///
        ///#constants
        ///
        ///def __getExt(fileName):
        ///    if &apos;.&apos; in fileName: return os.path.splitext(fileName)[1].replace(&apos;.&apos;, &apos;&apos;)
        ///    else: return fileName
        ///
        ///&quot;&quot;&quot;
        ///Methods for translating between mime-types and file extensions
        ///&quot;&quot;&quot;
        ///def getMimeType(fileName):
        ///    &quot;&quot;&quot;
        ///    Returns the mime type for the given file name
        ///    :param str fileName A file name, file extension or file path specification
        ///    &quot;&quot;&quot;
        ///    extension = __getExt(fileName)
        ///    #getMimeType body
        ///
        ///def [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PythonClass {
            get {
                return ResourceManager.GetString("PythonClass", resourceCulture);
            }
        }
    }
}
